Fix "undefined reference to stepperWait" compiler error on Arduino IDE 1.6.10 or newer
(cherry picked from commit cfcd9cb60f3df068a042fea08f1b5595e9474194)